Проверка деплоя

diff --git a/.github/workflows/deploy.yml b/.github/workflows/deploy.yml
--- a/.github/workflows/deploy.yml
+++ b/.github/workflows/deploy.yml
@@ -10,10 +10,24 @@ jobs:
     steps:
       - name: Checkout
         uses: actions/checkout@v4
+      - name: Тест SSH подключения
+        uses: appleboy/ssh-action@master
+        with:
+          host: ${{ secrets.SERVER_IP }}
+          username: ${{ secrets.SERVER_USER }}
+          key: ${{ secrets.SSH_PRIVATE_KEY }}
+          script: echo "Успешное подключение!"
 
       - name: Настройка SSH
         run: |
           mkdir -p ~/.ssh
+
+      - name: Проверка .prod.env
+        run: |
+          if [ ! -f .prod.env ]; then
+            echo "::error::.prod.env not found!"
+            exit 1
+          fi
 
       - name: отправка .prod.env
         uses: appleboy/scp-action@v1
